/**
 * Stub for Convex generated API.
 * This file is auto-generated by `npx convex dev` in cloud mode.
 * In self-hosted mode, it serves as a placeholder to prevent build errors.
 */

// biome-ignore lint: stub file for build compatibility
export const api = {} as any;
